// List of coin names organized by protocol type

const coins = {
  BTC: {
    VRSC: 'Verus',
    KMD: 'Komodo',
    BTC: 'Bitcoin',
    VOTE2019: 'VOTE2019',
    KSB: 'KSB',
    MORTY: 'Morty',
    RICK: 'Rick',
    OUR: 'Ourcoin',
    ILN: 'ILN',
    BET: 'BET',
    BOTS: 'BOTS',
    CEAL: 'CEAL NET',
    COQUI: 'COQUI',
    KMDICE: 'KMDICE',
    CHAIN: 'Chainmakers',
    GLXT: 'GLXToken',
    EQL: 'Equaliser',
    CRYPTO: 'CRYPTO',
    HODL: 'HODL',
    DEX: 'DEX',
    JUMBLR: 'JUMBLR',
    KV: 'KV',
    MGW: 'MultiGateway',
    MVP: 'MVP Lineup',
    //MNZ: 'Monaize',
    PANGEA: 'PANGEA',
    PGT: 'Pungo',
    REVS: 'REVS',
    MSHARK: 'MSHARK',
    //SHARK: 'SHARK',
    MESH: 'SpaceMesh',
    SUPERNET: 'SUPERNET',
    //WLC: 'WIRELESS',
    WLC21: 'WirelessCoin',
    AXO: 'AXO',
    ETOMIC: 'ETOMIC',
    BTCH: 'BTCH',
    BEER: 'BEER (Test coin)',
    PIZZA: 'PIZZA (Test coin)',
    //VOTE2018: 'VOTE2018 (Notary Elections)',
    NINJA: 'NINJA',
    GLXT: 'GLXToken',
    BNTN: 'Blocnation',
    PRLPAY: 'Pearl Pay',
    OOT: 'Utrum',
    ZILLA: 'ChainZilla',
    DSEC: 'DevSec',
    MGNX: 'MagnaX',
    CCL: 'CoinCollect',
    PIRATE: 'Pirate',
    KOIN: 'Koinon Coin',
    DION: 'DionPay',
    PTX: 'PatentTX',
    ZEXO: 'Zaddex',
    SPLTEST: 'Sapling Test Chain',
    LUMBER: 'Lumberscout',
    RFOX: 'Redfox Labs',
    HUSH: 'HUSH',
    LABS: 'LABS',
    MTST3: 'MTST3',
    DP: 'DigitalPrice',
    VRSCTEST: 'Verus Testnet',
    MTST3: 'MTST3',
    LABS: 'LABS',
    CLF: 'CryptoLeaf',
    KEA: 'KEA',
    OVAL: 'OVAL',
    TILE: 'TILE',
    TRET: 'TRET',
    JST: 'JST',
    DEC8: 'DEC8',
    //STRAT: 'Stratis',
    //TOA: 'TOA',
    //USC: 'UltimateSecureCash',
    //VPN: 'VpnCoin',
    //WC: 'WinCoin',
    //NRG: 'Energi',
    //ABY: 'ArtByte',
    //VOT: 'VoteCoin',
    //BDL: 'Bitdeal',
    BTCP: 'BitcoinPrivate',
    //MAC: 'Machinecoin',
    //XWC: 'Whitecoin',
    //XVC: 'Vcash',
    SMART: 'Smartcash',
    //CRAVE: 'Crave',
    //ACC: 'AdCoin',
    //AC: 'AsiaCoin',
    //AUR: 'Auroracoin',
    //BCA: 'Bitcoin Atom',
    //CLAM: 'Clams',
    //CLUB: 'ClubCoin',
    //DMD: 'Diamond',
    //EXCL: 'ExclusiveCoin',
    FTC: 'FeatherCoin',
    //FLASH: 'Flash',
    //NLG: 'Gulden',
    LCC: 'Litecoin Cash',
    MNX: 'MinexCoin',
    //NAV: 'NavCoin',
    //NEOS: 'NeosCoin',
    //OK: 'OKCash',
    //OMNI: 'OmniLayer',
    //PIVX: 'Pivx',
    //RDD: 'Reddcoin',
    UNO: 'Unobtanium',
    XVG: 'Verge',
    //VIVO: 'VIVO',
    //EFL: 'E-Gulden',
    //GBX: 'GoByte',
    //BSD: 'Bitsend',
    //LBC: 'LBRY Credits',
    //ERC: 'Europecoin',
    //BATA: 'Bata',
    EMC2: 'Einsteinium',
    //SYS: 'Syscoin',
    //IOP: 'Internet of People',
    //ZEN: 'Zencash',
    XZC: 'Zcoin',
    FJC: 'Fujicoin',
    GAME: 'GameCredits',
    //BCBC: 'Bitcoin CBC',
    BTG: 'BitcoinGold',
    BCH: 'BitcoinCash',
    DASH: 'Dash',
    //DNR: 'Denarius',
    DGB: 'DigiByte',
    FAIR: 'Faircoin',
    //ARG: 'Argentum',
    LTC: 'Litecoin',
    MONA: 'Monacoin',
    NMC: 'Namecoin',
    VTC: 'Vertcoin',
    VIA: 'Viacoin',
    SIB: 'Sibcoin',
    BLK: 'Blackcoin',
    DOGE: 'Dogecoin',
    ZEC: 'Zcash',
    HUSH: 'Hush',
    SNG: 'SnowGem',
    ZCL: 'Zclassic',
    XMY: 'Myriad',
    GRS: 'Groestlcoin',
    HODLC: 'Hodl coin',
    SUQA: 'SUQA',
    BTX: 'Bitcore',
    QTUM: 'Qtum',
    BTCZ: 'BitcoinZ',
    CHIPS: 'Chips',
    //MZC: 'Mazacoin',
    //ZET: 'Zetacoin',
    //SLR: 'Solarcoin',
    //SMLY: 'Smileycoin',
    //RBY: 'Rubycoin',
    //VOX: 'RevolutionVR',
    //PUT: 'PutinCoin',
    //POT: 'Potcoin',
    //POSW: 'Poswcoin',
    //PINK: 'Pinkcoin',
    //PSB: 'Pesobit',
    //NSR: 'NuShares',
    //NVC: 'Novacoin',
    //NYC: 'NewYorkCoin',
    //NRO: 'Neuro',
    //LYNX: 'Lynx',
    //LINX: 'Linx',
    //LDCN: 'Landcoin',
    //KOBO: 'Kobocoin',
    //IXC: 'Ixcoin',
    //INSN: 'InsaneCoin',
    //THC: 'Hempcoin',
    //HNC: 'Helleniccoin',
    //GRC: 'Gridcoin',
    //GCR: 'Global Currency Reserve',
    //FRST: 'FirstCoin',
    ERC: 'Europecoin',
    //EDRC: 'EDRcoin',
    //ECN: 'eCoin',
    //DGC: 'Digitalcoin',
    //DEFC: 'Defcoin',
    //CMP: 'CompCoin',
    //CCN: 'Cannacoin',
    //CDN: 'Canada eCoin',
    //BRIT: 'BritCoin',
    XBC: 'BitcoinPlus',
    //BELA: 'BelaCoin',
    //USNBT: 'NuBits',
    //ONX: 'Onixcoin',
    ZET: 'Zetacoin',
    //JBS: 'Jumbucks',
    //SLM: 'Slimcoin',
    AXE: 'Axe',
    //PPC: 'Peercoin',
    MZC: 'Mazacoin',
    //SDC: 'ShadowCash',
    BZC: 'Bitzec',
  },
  ETH: {
    ETH: 'Ethereum',
    //ETH_ROPSTEN: 'Ethereum Ropsten Testnet',
    AE: 'Aeternity',
    //AION: 'Aion',
    ANN: 'Agent Not Needed',
    BFT: 'BnkToTheFuture',
    BIO: 'BioCrypt',
    BITSOKO: 'Bitsoko',
    BLZ: 'Bluzelle',
    BOX: 'Beonbox',
    BTCL: 'BTC Lite',
    //BTM: 'Bytom',
    BTO: 'Bottos',
    CENNZ: 'Centrality',
    //CMT: 'CyberMiles',
    CS: 'Credits',
    CYFR: 'CyphrCoin',
    DATA: 'Streamr DATAcoin',
    ELD: 'Electrum Dark',
    ENG: 'Enigma',
    ETA: 'Etheera',
    ETK: 'EnergiToken',
    FOOD: 'FoodCoin',
    GMBEL: 'G-Mbel',
    GPN: 'GPN Coin',
    GROW: 'Grow',
    GTC: 'Game.com',
    GTO: 'Gifto',
    HT: 'Huobi Token',
    HTS: 'Hostingicos',
    ITL: 'Italian Lira',
    JOI: 'JointEDU',
    KICK: 'KickCoin',
    LIKE: 'LikeCoin',
    LINK: 'ChainLink',
    LTR: 'Labtorum',
    LYS: 'Lightyears',
    MAN: 'Matrix AI Network',
    MMX: 'Mechanix Token',
    MRPH: 'Morpheus Network',
    MTF: 'MintFlint Token',
    MYB: 'MyBit Token',
    NOAH: 'Noah Coin',
    NPXS: 'Pundi X',
    NS21: 'PeachCoin',
    //NULS: 'Nuls',
    OCC: 'Original Crypto Coin',
    PAO: 'Pacific Ocean',
    PCL: 'Peculium',
    PCNC: 'PCN Coin',
    PEP: 'PesaPepe',
    PGT: 'Puregold Token',
    POLY: 'Polymath',
    PURC: 'Peurcoin',
    QBIT: 'Qubitica',
    QKC: 'QuarkChain',
    RUFF: 'Ruff',
    RVT: 'Rivetz',
    SPANK: 'SpankChain',
    STRM41: 'Stream41',
    SUB: 'Substratum',
    SVD: 'Savedroid',
    THETA: 'Theta Token',
    TRAT: 'Tratok',
    CIX: 'Cryptonetix',
    DCN: 'Dentacoin',
    ELY: 'Elysian',
    DROP: 'Dropil',
    DRT: 'DomRaider',
    ELF: 'aelf',
    RLTY: 'SMARTRealty',
    PXT: 'Populous XBRL Token',
    STORM: 'Storm',
    TUSD: 'TrueUSD',
    WAX: 'WAX',
    KIN: 'Kin',
    LALA: 'LALA World',
    ONNI: 'Misericordae',
    PAT: 'Pangea Arbitration Token',
    USDT: 'Tether',
    BBT: 'Bitboost',
    OCT: 'Octus',
    OMG: 'OmiseGo',
    R: 'Revain',
    UCASH: 'U.CASH',
    //ICX: 'ICON',
    BNB: 'Binance Coin',
    BTK: 'BitcoinToken',
    DAI: 'Dai',
    DDD: 'Scry.info',
    DGD: 'DigixDAO',
    DGPT: 'DigiPulse',
    DRGN: 'Dragonchain',
    FLLW: 'FollowCoin',
    FSN: 'Fusion',
    HYD: 'Hydra',
    IOST: 'IOST',
    PPT: 'Populous',
    LRC: 'Loopring',
    MDS: 'MediShares',
    MKR: 'Maker',
    SNT: 'Status',
    REP: 'Augur',
    SRN: 'SIRIN LABS Token',
    YLC: 'YoloCash',
    ZRX: '0x',
    BAT: 'Basic Attention Token',
    ETHOS: 'Ethos',
    QASH: 'Qash',
    FUN: 'FunFair',
    KNC: 'Kyber Network',
    SALT: 'Salt',
    BNT: 'Bancor',
    ICN: 'Iconomi',
    LUPX: 'Lupecoin',
    //NAS: 'Nebulas',
    PAY: 'TenX',
    REQ: 'Request Network',
    STORJ: 'Storj',
    STWY: 'StorweeyToken',
    GNO: 'Gnosis',
    RLC: 'iExec RLC',
    ENJ: 'Enjin Coin',
    QSP: 'Quantstamp',
    RDN: 'Raiden Network Token',
    WTC: 'Waltonchain',
    CVC: 'Civic',
    SAN: 'Santiment',
    ANT: 'Aragon',
    LOOM: 'Loom Network',
    MANA: 'Decentraland',
    MCO: 'Monaco',
    MGO: 'MobileGo',
    MTL: 'Metal',
    EDG: 'Edgeless',
    MLN: 'Melon',
    AMB: 'Ambrosus',
    WINGS: 'Wings',
    POWR: 'Power Ledger',
    PRL: 'Oyster',
    RHOC: 'RChain',
    RCN: 'Ripio Credit Network',
    SANC: 'Sancoj',
    SNGLS: 'SingularDTV',
    TAAS: 'TaaS',
    DNT: 'District0x',
    CFI: 'Cofound.it',
    LUN: 'Lunyr',
    ADT: 'adToken',
    AST: 'AirSwap',
    CDT: 'Blox',
    TKN: 'TokenCard',
    HMQ: 'Humaniq',
    BCAP: 'Bcap',
    NMR: 'Numeraire',
    //NET: 'Nimiq',
    TRST: 'Trust',
    GUP: 'Matchpool',
    '1ST': 'FirstBlood',
    TIME: 'Chronobank',
    SWT: 'Swarm City',
    //VEN: 'VeChain',
    DICE: 'Etheroll',
    XAUR: 'Xarum',
    XOV: 'XOVBank',
    PLU: 'Pluton',
    HGT: 'HelloGold',
    VSL: 'vSlice',
    IND: 'Indorse Token',
    FYN: 'FundYourselfNow',
    //TODO: Get erc20 contract ID for eos
    //EOS: 'EOS',
    ZIL: 'Zilliqa',
    //OCALL: 'Old Capital',
    //CALLG: 'Capital GAS',
  },
};

module.exports = coins;
