export const testConfig = {
  host: "127.0.0.1",
  agamaPort: 17775,
  maxDescriptors: {
    darwin: 90000,
    linux: 1000000
  },
  dev: false,
  debug: false,
  roundValues: false,
  experimentalFeatures: true,
  dataDir: "",
  autoStartVRSC: false,
  autoStakeVRSC: false,
  stakeGuard: "",
  pubKey: "",
  dex: {
    walletUnlockTimeout: 3600
  },
  transactionCountPublic: 1000,
  transactionCountPrivate: 1000,
  cliStopTimeout: 1000,
  failedRPCAttemptsThreshold: 10,
  stopNativeDaemonsOnQuit: true,
  lang: "EN",
  rpc2cli: false,
  fiatRates: true,
  loadCoinsFromStorage: false,
  requirePinToConfirmTx: false,
  electrum: {
    maxVinParseLimit: 120,
    cache: false,
    proxy: false,
    socketTimeout: 10000,
    customServers: false,
    syncServerListFromKv: false,
    allowCustomFees: false,
    listtransactionsMaxLength: 10,
    csvListtransactionsMaxLength: 400
  },
  defaultFiatCurrency: "usd",
  native: {
    rpc2cli: false,
    cliStopTimeout: 30000,
    failedRPCAttemptsThreshold: 10,
    stopNativeDaemonsOnQuit: true,
    dataDir: "",
    listtransactionsMaxLength: 300,
    csvListtransactionsMaxLength: 1000,
    zlistreceivedbyaddress: true,
    zgetoperationresult: false,
    zshieldcoinbase: true
  },
  verus: {
    stakeGuard: "",
    autoStakeVRSC: false,
    pbaasTestmode: true
  },
  pbaasChains: [],
  reservedChains: ["SUPERNET",
  "REVS",
  "WLC",
  "PANGEA",
  "PGT",
  "DEX",
  "JUMBLR",
  "BET",
  "CRYPTO",
  "HODL",
  "MSHARK",
  "BOTS",
  "MGW",
  "MVP",
  "KV",
  "CEAL",
  "MESH",
  "COQUI",
  "KMDICE",
  "CHAIN",
  "GLXT",
  "EQL",
  "MNZ",
  "AXO",
  "ETOMIC",
  "BTCH",
  "BEER",
  "PIZZA",
  "OOT",
  "VOTE2018",
  "NINJA",
  "BNTN",
  "PRLPAY",
  "ZILLA",
  "DSEC",
  "MGNX",
  "CCL",
  "PIRATE",
  "KOIN",
  "DION",
  "PTX",
  "VRSC",
  "VRSCTEST",
  "SPLTEST",
  "LUMBER",
  "KMD",
  "KOMODO",
  "zcashd",
  "komodod",
  "chipsd",
  "CHIPS"],
  pubkey: "",
  exchanges: {
  coinswitchKey: ""
  },
  daemonOutput: false,
  token: "6e5b03e6f58c61f3baf94db4ef80a8a97e8b1ff7b6f25b78f879afbddb123d99"
}
