// Coin data/ledger
export const SET_COIN_BALANCES = 'SET_COIN_BALANCES'
export const SET_COIN_TRANSACTIONS = 'SET_COIN_TRANSACTIONS'
export const SET_COIN_INFO = 'SET_COIN_INFO'
export const SET_COIN_ADDRESSES = 'SET_COIN_ADDRESSES'
export const SET_COIN_MININGINFO = 'SET_COIN_MININGINFO'
export const SET_COIN_ZOPERATIONS = 'SET_COIN_ZOPERATIONS'
export const SET_COIN_DEFINEDCHAINS = 'SET_COIN_DEFINEDCHAINS'
export const SET_COIN_FIATPRICE = 'SET_COIN_FIATPRICE'
export const SET_FIATPRICE_CURRENCY = 'SET_FIATPRICE_CURRENCY'

// API Update data & parameters
export const SET_UPDATE_DATA = 'SET_UPDATE_DATA'
export const EXPIRE_DATA = 'EXPIRE_DATA'
export const RENEW_DATA = 'RENEW_DATA'
export const OCCUPY_API_CALL = 'OCCUPY_API_CALL'
export const FREE_API_CALL = 'FREE_API_CALL'
export const SET_EXPIRE_ID = 'SET_EXPIRE_ID'
export const CLEAR_EXPIRE_ID = 'CLEAR_EXPIRE_ID'
export const SET_UPDATE_EXPIRED_ID = 'SET_UPDATE_EXPIRED_ID'
export const CLEAR_UPDATE_EXPIRED_ID = 'CLEAR_UPDATE_EXPIRED_ID'
export const DISABLE_UPDATE_WARNING_SNACK = 'DISABLE_UPDATE_WARNING_SNACK'
export const ENABLE_UPDATE_WARNING_SNACK = 'ENABLE_UPDATE_WARNING_SNACK'

// Settings
export const SET_CONFIG = 'SET_CONFIG'
export const SET_CONFIG_SCHEMA = 'SET_CONFIG_SCHEMA'

// Errors
export const ERROR_COIN_BALANCES = 'ERROR_COIN_BALANCES'
export const ERROR_COIN_TRANSACTIONS = 'ERROR_COIN_TRANSACTIONS'
export const ERROR_COIN_INFO = 'ERROR_COIN_INFO'
export const ERROR_COIN_ADDRESSES = 'ERROR_COIN_ADDRESSES'
export const ERROR_COIN_MININGINFO = 'ERROR_COIN_MININGINFO'
export const ERROR_COIN_ZOPERATIONS = 'ERROR_COIN_ZOPERATIONS'
export const ERROR_COIN_DEFINEDCHAINS = 'ERROR_COIN_DEFINEDCHAINS'
export const ERROR_COIN_FIATPRICE = 'ERROR_COIN_FIATPRICE'
export const ERROR_ACTIVATE_COIN = 'ERROR_ACTIVATE_COIN'

// Navigation
export const SET_MAIN_NAVIGATION_PATH = 'SET_MAIN_NAVIGATION_PATH'
export const SET_MODAL_NAVIGATION_PATH = 'SET_MODAL_NAVIGATION_PATH'

// Coins
export const SET_ACTIVATED_COINS = 'SET_ACTIVATED_COINS'
export const SET_COIN_STATUS = 'SET_COIN_STATUS'
export const ACTIVATE_COIN = 'ACTIVATE_COIN'
export const DEACTIVATE_COIN = 'DEACTIVATE_COIN'
export const UNTRACK_COIN = 'UNTRACK_COIN'
export const REMOVE_COIN = 'REMOVE_COIN'

// Users/Authentication
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_DEFAULT_USER = 'SET_DEFAULT_USER'
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const ENABLE_START_WITH_LAST_COINS = 'ENABLE_START_WITH_LAST_COINS'
export const ENABLE_START_AT_LAST_LOCATION = 'ENABLE_START_AT_LAST_LOCATION'

// Modal
export const SET_MODAL_PARAMS = 'SET_MODAL_PARAMS'

// Snackbar
export const NEW_SNACKBAR = 'NEW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const SET_SNACK_TIMER = 'SET_SNACK_TIMER'

