// Coin data/ledger
export const SET_FIATPRICE_CURRENCY = 'SET_FIATPRICE_CURRENCY'
export const SET_COIN_BALANCES = 'SET_COIN_BALANCES'
export const SET_COIN_TRANSACTIONS = 'SET_COIN_TRANSACTIONS'
export const SET_COIN_RESERVE_TRANSFERS = 'SET_COIN_RESERVE_TRANSFERS'
export const SET_COIN_INFO = 'SET_COIN_INFO'
export const SET_COIN_ADDRESSES = 'SET_COIN_ADDRESSES'
export const SET_COIN_MININGINFO = 'SET_COIN_MININGINFO'
export const SET_COIN_ZOPERATIONS = 'SET_COIN_ZOPERATIONS'
export const SET_COIN_DEFINEDCHAINS = 'SET_COIN_DEFINEDCHAINS'
export const SET_COIN_CURRENTSUPPLY = 'SET_COIN_CURRENTSUPPLY'
export const SET_COIN_BLOCKREWARD = 'SET_COIN_BLOCKREWARD'
export const SET_COIN_FIATPRICE = 'SET_COIN_FIATPRICE'
export const SET_COIN_IDENTITIES = 'SET_COIN_IDENTITIES'
export const SET_COIN_ALL_CURRENCIES = 'SET_COIN_ALL_CURRENCIES'
export const SET_COIN_CURRENCY_DATA_MAP = 'SET_COIN_CURRENCY_DATA_MAP'
export const SET_COIN_NAME_COMMITMENTS = 'SET_COIN_NAME_COMMITMENTS'

// API Update data & parameters
export const SET_COIN_UPDATE_DATA = 'SET_COIN_UPDATE_DATA'
export const SET_SYSTEM_UPDATE_DATA = 'SET_SYSTEM_UPDATE_DATA'
export const EXPIRE_COIN_DATA = 'EXPIRE_COIN_DATA'
export const RENEW_COIN_DATA = 'RENEW_COIN_DATA'
export const OCCUPY_COIN_API_CALL = 'OCCUPY_COIN_API_CALL'
export const FREE_COIN_API_CALL = 'FREE_COIN_API_CALL'
export const SET_COIN_EXPIRE_ID = 'SET_COIN_EXPIRE_ID'
export const CLEAR_COIN_EXPIRE_ID = 'CLEAR_COIN_EXPIRE_ID'
export const SET_COIN_UPDATE_EXPIRED_ID = 'SET_COIN_UPDATE_EXPIRED_ID'
export const CLEAR_COIN_UPDATE_EXPIRED_ID = 'CLEAR_COIN_UPDATE_EXPIRED_ID'
export const DISABLE_UPDATE_WARNING_SNACK = 'DISABLE_UPDATE_WARNING_SNACK'
export const ENABLE_UPDATE_WARNING_SNACK = 'ENABLE_UPDATE_WARNING_SNACK'
export const SET_SYSTEM_UPDATE_INTERVAL_ID = 'SET_SYSTEM_UPDATE_INTERVAL_ID'
export const CLEAR_SYSTEM_UPDATE_INTERVAL_ID = 'CLEAR_SYSTEM_UPDATE_INTERVAL_ID'
export const OCCUPY_SYSTEM_API_CALL = 'OCCUPY_SYSTEM_API_CALL'
export const FREE_SYSTEM_API_CALL = 'FREE_SYSTEM_API_CALL'

// System data update intervals
export const SET_CPU_TEMP = 'SET_CPU_TEMP'
export const SET_CPU_LOAD = 'SET_CPU_LOAD'
export const SET_SYS_TIME = 'SET_SYS_TIME'

// Settings
export const SET_CONFIG = 'SET_CONFIG'
export const SET_CONFIG_SCHEMA = 'SET_CONFIG_SCHEMA'

// Errors
export const ERROR_ACTIVATE_COIN = 'ERROR_ACTIVATE_COIN'
export const ERROR_COIN_BALANCES = 'ERROR_COIN_BALANCES'
export const ERROR_COIN_TRANSACTIONS = 'ERROR_COIN_TRANSACTIONS'
export const ERROR_COIN_RESERVE_TRANSFERS = 'ERROR_COIN_RESERVE_TRANSFERS'
export const ERROR_COIN_INFO = 'ERROR_COIN_INFO'
export const ERROR_COIN_ADDRESSES = 'ERROR_COIN_ADDRESSES'
export const ERROR_COIN_MININGINFO = 'ERROR_COIN_MININGINFO'
export const ERROR_COIN_ZOPERATIONS = 'ERROR_COIN_ZOPERATIONS'
export const ERROR_COIN_DEFINEDCHAINS = 'ERROR_COIN_DEFINEDCHAINS'
export const ERROR_COIN_CURRENTSUPPLY = 'ERROR_COIN_CURRENTSUPPLY'
export const ERROR_COIN_BLOCKREWARD = 'ERROR_COIN_BLOCKREWARD'
export const ERROR_COIN_FIATPRICE = 'ERROR_COIN_FIATPRICE'
export const ERROR_COIN_IDENTITIES = 'ERROR_COIN_IDENTITIES'
export const ERROR_COIN_ALL_CURRENCIES = 'ERROR_COIN_ALL_CURRENCIES'
export const ERROR_COIN_CURRENCY_DATA_MAP = 'ERROR_COIN_CURRENCY_DATA_MAP'
export const ERROR_COIN_NAME_COMMITMENTS = 'ERROR_COIN_NAME_COMMITMENTS'
export const ERROR_CPU_TEMP = 'ERROR_CPU_TEMP'
export const ERROR_CPU_LOAD = 'ERROR_CPU_LOAD'
export const ERROR_SYS_TIME = 'ERROR_SYS_TIME'

// Navigation
export const SET_MAIN_NAVIGATION_PATH = 'SET_MAIN_NAVIGATION_PATH'
export const SET_MODAL_NAVIGATION_PATH = 'SET_MODAL_NAVIGATION_PATH'

// Coins
export const SET_ACTIVATED_COINS = 'SET_ACTIVATED_COINS'
export const SET_COIN_STATUS = 'SET_COIN_STATUS'
export const ACTIVATE_COIN = 'ACTIVATE_COIN'
export const DEACTIVATE_COIN = 'DEACTIVATE_COIN'
export const UNTRACK_COIN = 'UNTRACK_COIN'
export const REMOVE_COIN = 'REMOVE_COIN'

// Users/Authentication
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_DEFAULT_USER = 'SET_DEFAULT_USER'
export const ENABLE_START_WITH_LAST_COINS = 'ENABLE_START_WITH_LAST_COINS'
export const SET_STARTUP_OPTIONS = 'SET_STARTUP_OPTIONS'
export const ENABLE_START_AT_LAST_LOCATION = 'ENABLE_START_AT_LAST_LOCATION'
export const SELECT_CURRENCY_FOR_COIN = 'SELECT_CURRENCY_FOR_COIN'
export const SET_LOGOUT_USER = 'SET_LOGOUT_USER'
export const FINISH_LOGOUT_USER = 'FINISH_LOGOUT_USER'

// Modal
export const SET_MODAL_PARAMS = 'SET_MODAL_PARAMS'

// Snackbar
export const NEW_SNACKBAR = 'NEW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const SET_SNACK_TIMER = 'SET_SNACK_TIMER'

// System Data
export const SET_STATIC_DATA = 'SET_STATIC_DATA'

// Local Currency List Data 
export const SET_ALL_CURRENCY_BLACKLISTS = 'SET_ALL_CURRENCY_BLACKLISTS'
export const SET_ALL_CURRENCY_WHITELISTS = 'SET_ALL_CURRENCY_WHITELISTS'
export const SET_CURRENCY_BLACKLIST = 'SET_CURRENCY_BLACKLIST'
export const SET_CURRENCY_WHITELIST = 'SET_CURRENCY_WHITELIST'

// Debugging
export const LOG_WARNING = 'LOG_WARNING'

// Loading
export const START_LOADING_MINING_FUNCTIONS = 'SET_LOADING_MINING_FUNCTIONS'
export const FINISH_LOADING_MINING_FUNCTIONS = 'DISABLE_LOADING_MINING_FUNCTIONS'

// Text Dialog
export const OPEN_TEXT_DIALOG = 'OPEN_TEXT_DIALOG'
export const CLOSE_TEXT_DIALOG = 'CLOSE_TEXT_DIALOG'

// API Related Calls, for managing requests to local server api
export const ADD_CALLED_TIME = 'ADD_CALLED_TIME'
export const GET_POST_TICKET = 'GET_POST_TICKET'
export const SELECT_GET_WINNER = 'SELECT_GET_WINNER'
export const GET_GET_TICKET = 'GET_GET_TICKET'

